# Configuration for PMTable application
source.folder.path=C:\\Users\\ADMIN\\Desktop\\PM-data
destination.folder.path=C:\\Users\\ADMIN\\Desktop\\destinationFolder
jdbc.url=jdbc:postgresql://localhost:5432/PMTable
jdbc.username=postgres
jdbc.password=Sha123**